//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RisaAtelier.ProxyEnablementKit.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RisaAtelier.ProxyEnablementKit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [Error #2] .NET Framework Directory Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_DOTNET_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_DOTNET_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Error #1]Nuget.exe not found. (You need to download it to execute this tool) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_NUGET_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_NUGET_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Proxy Server Authentication Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INPUT_PROXY_PASS {
            get {
                return ResourceManager.GetString("MSG_INPUT_PROXY_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Proxy Server Authentication Password (Confirm) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INPUT_PROXY_PASS_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_INPUT_PROXY_PASS_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Proxy Server URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INPUT_PROXY_URL {
            get {
                return ResourceManager.GetString("MSG_INPUT_PROXY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Proxy Server Authentication User Name (If no authentication, keep empty) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INPUT_PROXY_USER {
            get {
                return ResourceManager.GetString("MSG_INPUT_PROXY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter UiPath Installed Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INPUT_TARGET_DIR {
            get {
                return ResourceManager.GetString("MSG_INPUT_TARGET_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select UiPath Edition (0: Enterprise 1:Community) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_UIPATH_TYPE {
            get {
                return ResourceManager.GetString("MSG_UIPATH_TYPE", resourceCulture);
            }
        }
    }
}
